# Generated by Django 5.0.4 on 2024-04-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author_table',
            fields=[
                ('author_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=50)),
                ('author_email', models.CharField(max_length=25)),
                ('author_mobile', models.CharField(max_length=20)),
                ('author_dob', models.DateField(default='')),
                ('author_address', models.CharField(max_length=250)),
                ('author_institute', models.CharField(max_length=100)),
                ('author_designation', models.CharField(max_length=50)),
                ('author_password', models.CharField(max_length=90)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'author_table',
            },
        ),
        migrations.CreateModel(
            name='ea_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ea_name', models.CharField(max_length=50)),
                ('ea_email', models.CharField(max_length=50)),
                ('ea_phone', models.CharField(default='', max_length=20)),
                ('ea_dob', models.DateField(default='')),
                ('ea_teacherid', models.CharField(max_length=20)),
                ('ea_journalname', models.CharField(max_length=100)),
                ('ea_type', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=90)),
                ('otp', models.IntegerField()),
                ('verification', models.BooleanField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'ea_table',
            },
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_mobile', models.CharField(max_length=25)),
                ('user_password', models.CharField(max_length=90)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
