# Generated by Django 5.0.4 on 2024-04-30 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept_table',
            fields=[
                ('dept_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'dept_table',
            },
        ),
        migrations.AlterField(
            model_name='author_table',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='author_table',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ea_table',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ea_table',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='article_table',
            fields=[
                ('article_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
                ('author_name', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.author_table')),
            ],
            options={
                'db_table': 'article_table',
            },
        ),
        migrations.CreateModel(
            name='art_visit',
            fields=[
                ('art_visit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avisit_date', models.DateField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
                ('article_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.article_table')),
            ],
            options={
                'db_table': 'art_visit',
            },
        ),
        migrations.CreateModel(
            name='art_dld',
            fields=[
                ('dld_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dld_date', models.DateField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
                ('article_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.article_table')),
            ],
            options={
                'db_table': 'art_dld',
            },
        ),
        migrations.CreateModel(
            name='author_colab',
            fields=[
                ('colab_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('second_author', models.CharField(max_length=50)),
                ('third_author', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
                ('author_name', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.author_table')),
            ],
            options={
                'db_table': 'author_colab',
            },
        ),
        migrations.AddField(
            model_name='article_table',
            name='colab_id',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.author_colab'),
        ),
        migrations.CreateModel(
            name='issue_table',
            fields=[
                ('issue_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('issue_no', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
                ('volume_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.dept_table')),
            ],
            options={
                'db_table': 'issue_table',
            },
        ),
        migrations.AddField(
            model_name='article_table',
            name='issue_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.issue_table'),
        ),
        migrations.CreateModel(
            name='journal_table',
            fields=[
                ('journal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('journal_name', models.CharField(max_length=50)),
                ('journal_aim', models.TextField()),
                ('journal_ethics', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
                ('dept_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.dept_table')),
            ],
            options={
                'db_table': 'journal_table',
            },
        ),
        migrations.CreateModel(
            name='gl_table',
            fields=[
                ('gl_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=90)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
                ('journal_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.journal_table')),
            ],
            options={
                'db_table': 'gl_table',
            },
        ),
        migrations.CreateModel(
            name='eb_table',
            fields=[
                ('board_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
                ('id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.ea_table')),
                ('journal_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.journal_table')),
            ],
            options={
                'db_table': 'eb_table',
            },
        ),
        migrations.CreateModel(
            name='journal_visit',
            fields=[
                ('journal_visit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jvisit_date', models.DateField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
                ('journal_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.journal_table')),
            ],
            options={
                'db_table': 'journal_visit',
            },
        ),
        migrations.CreateModel(
            name='uaa',
            fields=[
                ('access_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_date', models.DateField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
                ('article_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.article_table')),
                ('user_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.user_table')),
            ],
            options={
                'db_table': 'uaa',
            },
        ),
        migrations.CreateModel(
            name='volume_table',
            fields=[
                ('volume_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('volume_no', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
                ('journal_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.journal_table')),
            ],
            options={
                'db_table': 'volume_table',
            },
        ),
    ]
