# Generated by Django 5.0.4 on 2024-06-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eb_table',
            name='editor_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='eb_table',
            name='editor_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='eb_table',
            name='editor_mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='eb_table',
            name='editor_name',
            field=models.CharField(max_length=50),
        ),
    ]
