# Generated by Django 5.0.4 on 2024-05-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_table',
            name='author_email',
            field=models.CharField(max_length=90),
        ),
    ]
