# Generated by Django 5.0.4 on 2024-05-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_table',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
