# Generated by Django 5.0.4 on 2024-04-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_dept_table_alter_author_table_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_table',
            name='journal_update',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='journal_table',
            name='update_link',
            field=models.CharField(default='', max_length=60),
        ),
    ]
