# Generated by Django 5.0.4 on 2024-05-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ea_table',
            name='ea_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ea_table',
            name='ea_mobile',
            field=models.CharField(default='', max_length=20),
        ),
    ]
