# Generated by Django 5.0.4 on 2024-05-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_alter_author_table_author_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept_table',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dept_table',
            name='status',
        ),
        migrations.AddField(
            model_name='ea_table',
            name='employee_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ea_table',
            name='ea_email',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='ea_table',
            name='ea_type',
            field=models.CharField(default='', max_length=70),
        ),
    ]
