# Generated by Django 5.0.4 on 2024-06-04 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_journal_table_issn_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_table',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='review_table',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
                ('article_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.article_table')),
                ('editor_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.ea_table')),
            ],
            options={
                'db_table': 'review_table',
            },
        ),
    ]
