# Generated by Django 5.0.4 on 2024-05-15 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0003_alter_journal_table_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_table',
            name='editor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.ea_table'),
        ),
    ]
