# Generated by Django 5.0.4 on 2024-05-11 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0003_remove_dept_table_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='role_id',
        ),
        migrations.AddField(
            model_name='usertable',
            name='seat_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.seat_table'),
        ),
    ]
