# Generated by Django 5.0.4 on 2024-05-26 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0003_ea_table_ea_address_ea_table_ea_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_table',
            name='editor',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.ea_table'),
        ),
    ]
