# Generated by Django 5.0.4 on 2024-05-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0004_remove_usertable_role_id_usertable_seat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ea_table',
            name='ea_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
