# Generated by Django 5.0.4 on 2024-06-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0004_article_table_ea_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation_table',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='role_table',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='seat_table',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='usertable',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
