# Generated by Django 5.0.4 on 2024-05-27 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0004_alter_journal_table_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_table',
            fields=[
                ('msg_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('msg_name', models.CharField(max_length=50)),
                ('msg_email', models.CharField(max_length=90)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=50)),
                ('ea_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.ea_table')),
                ('journal_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.journal_table')),
            ],
        ),
    ]
