# Generated by Django 5.0.4 on 2024-05-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0004_journal_table_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_table',
            name='journal_page',
            field=models.CharField(default='', max_length=150),
        ),
    ]
