# Generated by Django 5.0.4 on 2024-05-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0005_message_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message_table',
            table='message_table',
        ),
    ]
