# Generated by Django 5.0.4 on 2024-05-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0005_alter_ea_table_ea_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ea_table',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='ea_table',
            name='token',
            field=models.CharField(default='', max_length=90),
        ),
    ]
