# Generated by Django 5.0.4 on 2024-06-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0005_designation_table_status_role_table_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation_table',
            name='status',
        ),
        migrations.RemoveField(
            model_name='role_table',
            name='status',
        ),
        migrations.RemoveField(
            model_name='seat_table',
            name='status',
        ),
    ]
