# Generated by Django 5.0.4 on 2024-05-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0006_alter_message_table_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume_table',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='issue_table',
            name='cover_image',
            field=models.ImageField(default='', upload_to='issue_covers/'),
        ),
    ]
