# Generated by Django 5.0.4 on 2024-05-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0006_remove_journal_table_journal_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume_table',
            name='volume_no',
        ),
        migrations.AddField(
            model_name='volume_table',
            name='volume',
            field=models.CharField(default='', max_length=50),
        ),
    ]
