# Generated by Django 5.0.4 on 2024-05-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0007_remove_volume_table_volume_no_volume_table_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume_table',
            name='cover_image',
            field=models.ImageField(default='', upload_to='volume_covers/'),
        ),
    ]
