# Generated by Django 5.0.4 on 2024-06-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0007_alter_article_table_author2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_table',
            name='author_designation',
        ),
    ]
