# Generated by Django 5.0.4 on 2024-06-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0008_remove_author_table_author_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_table',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
