# Generated by Django 5.0.4 on 2024-05-20 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0008_alter_volume_table_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_table',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=25)),
                ('journal_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='admin_module.journal_table')),
            ],
            options={
                'db_table': 'notification_table',
            },
        ),
    ]
