# Generated by Django 5.0.4 on 2024-06-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0009_alter_notification_table_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_table',
            name='current_page_number',
            field=models.IntegerField(default=1),
        ),
    ]
