# Generated by Django 5.0.4 on 2024-05-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0009_notification_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal_table',
            name='journal_update',
        ),
        migrations.RemoveField(
            model_name='journal_table',
            name='update_link',
        ),
    ]
