# Generated by Django 5.0.4 on 2024-05-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0010_remove_journal_table_journal_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_table',
            name='email',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AddField(
            model_name='journal_table',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
