# Generated by Django 5.0.4 on 2024-06-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0010_issue_table_current_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_table',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ea_table',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author_table',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ea_table',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
