# Generated by Django 5.0.4 on 2024-05-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0011_journal_table_email_journal_table_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_table',
            name='author1',
            field=models.CharField(default='1', max_length=90),
        ),
        migrations.AddField(
            model_name='article_table',
            name='author2',
            field=models.CharField(default='1', max_length=90),
        ),
        migrations.AddField(
            model_name='article_table',
            name='author3',
            field=models.CharField(default='1', max_length=90),
        ),
    ]
