# Generated by Django 5.0.4 on 2024-06-18 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0011_author_table_token_expiry_ea_table_token_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ea_table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ea_table',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='author_table',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dept_table',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
