# Generated by Django 5.0.4 on 2024-06-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0012_ea_table_created_at_ea_table_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_table',
            name='current_page_number',
            field=models.IntegerField(default=1),
        ),
    ]
