# Generated by Django 5.0.4 on 2024-05-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0012_article_table_author1_article_table_author2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_table',
            old_name='author_name',
            new_name='author_id',
        ),
    ]
