# Generated by Django 5.0.4 on 2024-06-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0013_article_table_current_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_table',
            name='current_page_number',
            field=models.IntegerField(default=''),
        ),
    ]
