# Generated by Django 5.0.4 on 2024-05-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0013_rename_author_name_article_table_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eb_table',
            name='photo',
            field=models.ImageField(default='', upload_to='eb_photos/'),
        ),
    ]
