# Generated by Django 5.0.4 on 2024-06-18 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0014_alter_article_table_current_page_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_table',
            name='current_page_number',
        ),
    ]
