# Generated by Django 5.0.4 on 2024-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0014_eb_table_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_table',
            name='article_file',
            field=models.FileField(default='', upload_to='articles/'),
        ),
    ]
