# Generated by Django 5.0.4 on 2024-06-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0017_remove_article_table_current_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_table',
            name='starting_page_number',
            field=models.IntegerField(default=1),
        ),
    ]
