# Generated by Django 5.0.4 on 2024-06-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0018_article_table_starting_page_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal_table',
            old_name='logo',
            new_name='banner',
        ),
    ]
